### ISSUE TITLE
AWS Access Forbidden even for public data

### ISSUE THREAD

**Issue by nikparth** [brain-score/brain-score#183]
Hi I've been trying to run the brain-score tools and just want to use the public data but when I try to use `get_assembly()` with any of the public data, I'm getting an error: 

`File "/home/np1742/pytorchenv/lib/python3.6/site-packages/brainio_collection/fetch.py", line 66, in fetch
    self.download_boto()
  File "/home/np1742/pytorchenv/lib/python3.6/site-packages/brainio_collection/fetch.py", line 84, in download_boto
    raise Exception([e_signed, e_unsigned])
Exception: [ClientError('An error occurred (403) when calling the HeadObject operation: Forbidden',), ClientError('An error occurred (403) when calling the HeadObject operation: Forbidden',)]` 
If you could help figure this out that would be much appreciated as I'd love to play around with these tools more for my own work.

**Comment by nikparth** [comment]
This seems to be a problem just with the stimulus_sets, as the fetch_assembly() works but the fetch_stimulus_set function runs into this forbidden error.

**Comment by mschrimpf** [comment]
This issue seems to be confirmed by our unit tests: https://travis-ci.com/brain-score/brainio_collection/jobs/274753908
I cannot reproduce it locally though. I'm guessing it has something to do with recent changes in the AWS VPC security settings @jjpr-mit

**Comment by mschrimpf** [comment]
@nikparth if you try now, it should work (travis builds are passing, so we're confident it works).

---

internally @jjpr-mit: right now the SQL join only looks for _all_ zip files that contain a particular `image_id`.
Instead, what we need to do is look for the zip file that contains a particular `image_id` _given a StimulusSet name_.

**Comment by nikparth** [comment]
@mschrimpf thanks for the quick response- I ran through all of the public benchmarks and it seems to work fine for the MajajV4 and MajajIT but I seem to get the same error as above for the FreemanZiemba V1/V2 benchmarks. Not sure if that's expected right now and if only the Majaj data is working, but wanted to let you know in case the V1/V2 benchmarks should be working.

**Comment by mschrimpf** [comment]
should be fine now, can you confirm @nikparth?

**Comment by nikparth** [comment]
Yup @mschrimpf confirming works now.
