### ISSUE TITLE
submission: deal with dots in zip filenames

### ISSUE THREAD

**Issue by mschrimpf** [brain-score/brain-score#210]
E.g. `FileNotFoundError: [Errno 2] No such file or directory: '/net/storage001.ib.cluster/om2/group/dicarlo/jenkins/configs/cornet-v1.1-master.zip'` fails because there is a `.` in the name and we're splitting the zip file name based on the dot to cut the .zip.

**Comment by franzigeiger** [comment]
I fixed this in jenkins, it works as expected now.
