### ISSUE TITLE
why is ceiled score lower than unceiled? 

### ISSUE THREAD

**Issue by nikparth** [brain-score/brain-score#228]
https://github.com/brain-score/brain-score/blob/cddf89f553b4cb9a314c8fb6627b437df3eda121/brainscore/benchmarks/__init__.py#L101

It seems that all of the ceiled scores are lower than the unceiled. This intuitively doesn't make much sense to me because the ceiling is always less than 1.0 and so in the code (referenced above), the ceiled score should be the raw / ceiling which should be larger than raw because the raw is measured against 1.0 as a ceiling (at least for the regression correlation).  Am I missing something here?

**Comment by mschrimpf** [comment]
The neural benchmarks actually compute explained variance, i.e. `(r / c)^2` which can lead to ceiled scores being lower than unceiled: https://github.com/brain-score/brain-score/blob/cddf89f553b4cb9a314c8fb6627b437df3eda121/brainscore/benchmarks/_neural_common.py#L43-L53

**Comment by nikparth** [comment]
Ah thanks.
