### ISSUE TITLE
Data not found

### ISSUE THREAD

**Issue by donghaiwang** [brain-score/brain-score#245]
When I run the first example,
`import brainscore
data = brainscore.get_assembly("dicarlo.MajajHong2015")`

brainio_collection.assemblies.AssemblyLookupError: A DataAssembly named dicarlo.MajajHong2015 was not found.

How can I fix it? Thanks.

**Comment by mschrimpf** [comment]
It looks like you have already found the answer yourself, but in case others also run into this:
The example has been updated, please use the assembly identifier `"dicarlo.MajajHong2015.public"`.
