### ISSUE TITLE
Download data error

### ISSUE THREAD

**Issue by donghaiwang** [brain-score/brain-score#257]
When I run the first demo, 'brainscore.get_assembly("dicarlo.MajajHong2015")', it occurs a download data error. How can I fix it, thanks.

botocore.exceptions.NoCredentialsError: Unable to locate credentials

**Comment by mschrimpf** [comment]
Hi, were you able to resolve this? The identifier should be "dicarlo.MajajHong2015.**public**" (https://github.com/brain-score/brain-score/blob/master/examples/data.ipynb)
