### ISSUE TITLE
PCA in model scoring

### ISSUE THREAD

**Issue by yugrao** [brain-score/brain-score#282]
When is PCA run on the model? Is it possible to turn off the PCA step?

**Comment by mschrimpf** [comment]
there are two stages with different "kinds" of PCA:
1. in the **layer selection**, i.e. finding a layer to commit to cortical regions. [model-tools](https://github.com/brain-score/model-tools) uses [PCA on layer activations](https://github.com/brain-score/model-tools/blob/b5c7f300dc20fa9d7c338ee0d930524ea6e7e2bf/model_tools/brain_transformation/neural.py#L70) before comparing them with neural data to keep the sizes manageable
2. in the **pls metric**, i.e. to compare model predicted activity for a region with recorded activity. The [pls_regression](https://github.com/brain-score/brain-score/blob/4513ccaf170c8cb5384a6040866f5a389ce6cc4f/brainscore/metrics/regression.py#L74) used in several metrics performs dimensionality reduction as part of its fitting procedure
