### ISSUE TITLE
Error with Tensorflow version 

### ISSUE THREAD

**Issue by Aakashagr** [brain-score/brain-score#313]
Hello, 

I receive the following error while installing the dependencies

ERROR: Could not find a version that satisfies the requirement tensorflow==1.15 (from model-tools) (from versions: 2.5.0rc0, 2.5.0rc1, 2.5.0rc2, 2.5.0rc3, 2.5.0, 2.5.1, 2.5.2, 2.6.0rc0, 2.6.0rc1, 2.6.0rc2, 2.6.0, 2.6.1, 2.6.2, 2.7.0rc0, 2.7.0rc1, 2.7.0, 2.8.0rc0)
ERROR: No matching distribution found for tensorflow==1.15

**Comment by raj-magesh** [comment]
Hey Aakash, in case you didn't solve this, try using Python 3.7.

**Comment by mschrimpf** [comment]
Hi @Aakashagr, were you able to resolve this issue with @raj-magesh's suggestion?

**Comment by Aakashagr** [comment]
Hi Martin, I have not been able to work on this for now. But I suppose that it might work. Thanks for your inputs Raj

**Comment by mschrimpf** [comment]
ok reopen this issue if you run into issues!
