### ISSUE TITLE
How are the networks trained?

### ISSUE THREAD

**Issue by themrzmaster** [brain-score/brain-score#315]
Hi,
I have a really simple question which I could not find the answer on the website.
When we propose a network architecture we don't train the network? It's cross validated server-side only?
Is it optimized using SGD? 
Example: https://github.com/brain-score/candidate_models/blob/master/examples/score-model.ipynb here we define a new model but we don't train it on any dataset.
Did I get something wrong? Thanks

**Comment by mschrimpf** [comment]
Hi @themrzmaster,

The model specification is entirely up to the user -- they can choose to submit a trained or untrained model (with standard models, [training does improve match-to-brain](https://openreview.net/forum?id=g1SzIRLQXMM) though).
To include weights, there are different options, see e.g. https://github.com/brain-score/sample-model-submission/issues/13

Thank you for pointing out the example, we should make it clear there that it's just a dummy model to show-case the scoring process.
