### ISSUE TITLE
Error: cannot import name 'score_model' from 'brainscore'

### ISSUE THREAD

**Issue by maytusp** [brain-score/brain-score#324]
Hi Martin,

I installed brainscore library in a new machine and found this error. 

`cannot import name 'score_model' from 'brainscore'`

BrainScore in an old machine works normally.
Is it because of the latest update?

**Comment by mschrimpf** [comment]
Hi maytusp,

this should still work -- are you able to `import brainscore`? When you `dir(brainscore)`, do you see `score_model` as one of the items? Perhaps you are importing a different package that is also called `brainscore`?

**Comment by maytusp** [comment]
Hi Martin,
Thanks for a very quick reply, it's just my mistake that I create a python file named brainscore.py in that folder.
The script imports this file instead of the actual brain-score library.
